/** @type {import('tailwindcss').Config} */

module.exports = {
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        primary: "#3bb77e",
        ["primary-dark"]: "#2b8a5e",
        ["primary-light"]: "#4fc08d",
        secondary: "#c72b98",
        ["secondary-dark"]: "#a21e7c",
        ["secondary-light"]: "#d13daa",
        error: "#dc2626",
        ["error-dark"]: "#b91c1c",
        ["error-light"]: "#ef4444",
        info: "#0891b2",
        ["info-dark"]: "#0e7490",
        ["info-light"]: "#06b6d4",
        success: "#16a34a",
        ["success-dark"]: "#15803d",
        ["success-light"]: "#22c55e",
        warning: "#ea580c",
        ["warning-dark"]: "#c2410c",
        ["warning-light"]: "#f97316",
        1: "#fddde4",
        2: "#cdebbc",
        3: "#d1e8f2",
        4: "#cdd4f8",
        5: "#f6dbf6",
        6: "#fff2e5",
        7: "#d77f7a",
        8: "#63a2c1",
        9: "#f2fce4",
        10: "#fffceb",
        11: "#ecffec",
        12: "#feefea",
        13: "#fff3eb",
        14: "#fff3ff",
        15: "#f2fce4",
      },
      backgroundImage: {
        "slider-1": "url('/slider/slider-1.png')",
        "slider-2": "url('/slider/slider-2.png')",
      },
      screens: {
        xs: "480px",
      },
    },
  },
  plugins: [require("@tailwindcss/typography")],
  screens: {
    xs: "480px",
    sm: "576px",
    md: "768px",
    lg: "992px",
    xl: "1200px",
    "2xl": "1400px",
  },
  fontFamily: {
    sans: ["Inter", "sans-serif"],
    serif: ["Merriweather", "serif"],
  },
};
